### ISSUE TITLE
what language are the released zip/tgz files in ?

### ISSUE THREAD

**Issue by yamcenutzer** [mateidavid/zstr#19]
Am I missing something?
zstr.zip/tgz  doesn't seem to be cpp since some if not most the logical operators have been translated to their lexical counterparts, thus rendering the lib useless for use in e.g. vcpkg:
Example from near the beginning of strict_fstream.hpp
.....
line 63                res += (not res.empty()? "|" : "");
line 72        if ((mode & std::ios_base::trunc) and not (mode & std::ios_base::out))
...
and lot's more

**Comment by lczech** [comment]
As far as I see, this is still valid C++ code. The keyword-like forms of these operators (their "lexical" form) is totally fine: https://en.cppreference.com/w/cpp/language/operator_logical
So, the issue then might be that vcpkg does not implement the standard correctly, it seems.

**Comment by yamcenutzer** [comment]
Seriously?, Which c++ compiler compiles that? maybe you could give me an example?
And why is the actual source code (not the one in the zip package) proper c++?
Thx,

**Comment by lczech** [comment]
These alternative keywords actually come from ancient C, when not all keyboards were guaranteed to have `&`, `|`, etc. See this discussion: https://stackoverflow.com/questions/2376448/the-written-versions-of-the-logical-operators

So, it should work with all compilers. I just tested the zlib code with gcc and clang, works fine.

As for why that is used in the zip package - I don't know, not my code. We'd have to wait for response from @mateidavid 

Fun side note: Because these tokens are absolutely identical to their normal counterparts, you can also use `and` instead of `&&` as an r-value reference:

```cpp
void my_weird_function( std::vector<std::string> and vec )
{
    std::cout << vec.size() << "\n";
}
```

But please don't do this ;-)

**Comment by yamcenutzer** [comment]
Wow 
This is creepy and unreadable and at least msvc doesn't like it.
have to stop using that.

**Comment by ferdymercury** [comment]
Latest release seems to have this issue fixed:

```
res += (! res.empty()? "|" : "");
if ((mode & std::ios_base::trunc) && ! (mode & std::ios_base::out))
```
